export {
  AdministrationModule,
  AiContentModule,
  AnalyticsModule,
  ContentModule,
  CurriculumModule,
  EvaluationModule,
  GamificationModule,
  IdentityAccessModule,
  LearningModule,
  MasteryModule,
  NotificationsModule,
  PracticeModule,
  ReviewModule,
  StudyActivityModule,
  UserProfileModule,
} from './modules.js';
